zencart/documentation

Contributing/main/coding_standards.md
notes about separating markup, logic and display.
=> Clarify best-practice around not-embedding HTML in echo-statements

content/dev/Contributing/_index.md
Autogeneration (with ordering done via weight) is the way to go here.
=> Contributing page links not working

content/dev/Code/Modules/_index.md, content/dev/Code/Modules/order_total_modules.md, content/dev/Code/Modules/shipping_modules.md, content/dev/Code/_index.md
These are 1.x related files and should be on the /dev site. 
cc @lat9
=> Move Cindy's Shipping and OT docs out of V2

content/user/troubleshooting/debug_logs.md
Identify the **zc156-specific** formatting of a log-entry and how to 'divine' what happened from a log's contents.
=> Docs: How to 'read' a debug-log

content/user/admin/centerboxes.md, content/user/admin_pages/catalog/option_name_manager.md, content/user/admin_pages/discounts/coupon_restrictions.md, content/user/first_steps/hosting.md, content/user/first_steps/secure_access.md, content/user/first_steps/server_requirements.md, content/user/first_steps/yes_you_need_ssl.md, content/user/installing/installing_misc.md, content/user/installing/move_cart.md, content/user/new_user_topics/no_such_file.md, content/user/new_user_topics/overrides.md, content/user/payment/paypal_misc.md, content/user/performance/max_file_upload.md, content/user/performance/speed_up_site.md, content/user/plugins/best_plugin.md, content/user/products/attributes.md, content/user/products/downloadable.md, content/user/products/products_misc.md, content/user/template/basic_customizations.md, content/user/template/template_overrides.md, content/user/troubleshooting/cant_stay_logged_in_admin.md, content/user/troubleshooting/security_error.md, content/user/troubleshooting/strict_error_reporting.md, content/user/troubleshooting/troubleshooting_misc.md, content/user/troubleshooting/warning_headers_already_sent.md
When following unformatted text this is required or display will not be correct.
Following formatted text (a header for example) it's optional - I did it in a few cases here because I was worried about copy and paste or removing formatting. 
A few other small changes are included if I was fixing a bulleted list in the same file but this is mostly the bulleted list fix.
=> Bulleted lists must be preceded by blank line

layouts/user/baseof.html
Resolves html validation by including the title twice in the `<head>` and fixes #232.
=> Remove duplicate title tag

content/user/running/backup.md
This export information assumes that one is effectively already using phpMyAdmin version 4.4 and above; however, this does not cover those that are upgrading from an older version to such a "current" or newer version or even if not so upgrading immediately at least coming from an older version.  Being able to retrieve data from a historical system and having that instruction available is paramount to maintaining Zen Cart operation without having to rebuild the database...
=> Provide a link to more detailed settings

content/user/admin_pages/localization/languages.md
I have made some changes to this page to add some more examples and make it so that i think it works. I have also added a bit on troubleshooting as i have been trying to make it work with the minimum of details. I was wondering if on installing a language pack we should first get the user to copy over all of the english files this way if the language pack is missing files or zen cart base has added new files they will not be missing when the language pack is installed. I do not know if this is the final version so please be as harsh as you like and let me know what needs changing so that i can get it right.
=> Modified to bring in line with 1.5.7

config.toml, layouts/codepage/README.txt, layouts/codepage/content.html, layouts/dev/baseof.html, layouts/dev/content.html, layouts/partials/morehelp.html, layouts/user/baseof.html
Turn off right sidebar; edit option is now in the footer for all pages.  This makes individual pages much wider and makes it easy to show code blocks without wrapping.
=> Use the same more help text block in all pages in the footer.

content/user/admin/_index.md, content/user/admin/admin_password.md, content/user/troubleshooting/_index.md, layouts/partials/hooks/head-end.html
Right now a search for "Resetting" brings back a bunch of dups because of the presence of this string in the _index files and a redirect page.  Let's try excluding those pages and see if the match performance is better.
If so, make this same change in other redirect / _index files.
=> Try excluding pages from search

content/user/email/add_message.md
If the store owner has not edited the email_extras.php file in the basic includes/languages/english folder,  They will not find the file in an override folder.  Best to tell them to save the original in the override folder or, if the file IS there, edit the EMAIL_ORDER_MESSAGE.
=> email_extras.php not located in an override folder

content/user/new_user_topics/change_header_logo.md
Using px, em, or any other thing but a digit throws an HTML error.
It would be best to completely remove the width and height defines in the responsive world we live in today but, would the store owner know where to control the width and height?  Or, do we just leave it up to the responsive.css telling it {width:100%;height:auto;}?
=> Change addition of px on image width and height

content/user/email/advanced_email_troubleshooting.md
DMARC is the answer we were all looking for years ago when AOL, AT&T, sbcglobal, and others were simply throwing e-mail in the bit bucket without notifying a soul.
Although it is not mandatory for the receiver to follow the instructions, the inclusion in a site's DNS greatly increases email acceptance and really speeds up blacklist avoidance/removal.
=> Clarify SPF, DKIM, and add DMARC to DNS entries for email

content/user/email/advanced_email_troubleshooting.md
SPF and DKIM were done in the standard "here's what it is, and here's the acronym."  Missed that on DMARC somehow.  Probably lost it in the trifocals
=> Change DMARC listing to conform with other style

content/user/images/additional_images.md
At first glance, using the current display for the link, it looks as if the link is going to the site it is already on.
It actually goes to a page titled "Image Filename conventions" (sic)  which should be "Image Filename Conventions"
=> Link appears to go to the same page

content/user/installing/permissions.md
Added /zc_install/includes/nginx_conf to list of folders that need to be writable for installation
=> Doc change for issue #4538

assets/scss/_styles_project.scss
Currently, the links in the footer of the docs do not meet the 4.5:1 ratio for color contrast and are even worse when you hover on them.
This fix keeps the background color and changes the font colors for the a and a:hover to bring them into compliance.
=> Correct Color Contrast for Footer Links

.gitmodules, config.toml, go.mod, go.sum
Fixes 
WARN 2022/09/16 07:09:46 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
Updated docsy using 
https://www.docsy.dev/docs/updating/convert-site-to-module/
=> Fix template issue

content/dev/plugins/upgrading_to_158.md
Dynamic property update deprecation means you cannot simply create an objectInfo and get an object with arbitrary fields.
=> Updates for extending objectInfo

content/dev/plugins/encapsulated_plugins/sql_installation.md
This relates to zen cart fix #5229
I hope I have this correct. The SQL Installer Classes does not want to return to the beginning of the line.
=> Updated for SqlPatchInstaller change on zen cart

content/dev/code/158_language_files.md
Doc clarification, fixes #988.
At least two people felt the docs dictating how the new system works weren't explanatory enough about how the old system still works.  I've rearranged the well written original text into a slightly different order to bring these facts to light earlier.
=> Move note about old system still working higher up in the document

content/dev/code/158_language_files.md
[best practices](https://stackify.com/php-performance-optimization-guide/#:~:text=single%20and%20double%20quote%20usage%20matters) indicate single quotes should always be used if there are `vars` contained in the string.
=> replace double quotes with single quotes

content/dev/code/Modules/shipping_modules.md
Changes to identify how a shipping-module indicates "no quotes available", as requested in [this](https://github.com/zencart/zencart/issues/5979) Zen Cart GitHub issue.
=> Shipping modules update

content/dev/code/database_querying.md
Invalid PHP was used in both demonstrations of how not to use queries and how to use.
(There was a missing '(' ')' pairing.)
=> Update database querying examples

content/dev/code/php_idioms.md
The operator is similar to `isset`, not `!empty`.  Correcting the alternate-implementation example.
=> PHP Idioms/Null Coalescing Operator

content/user/template/basic_customizations.md
The current documentation names only seven, just adding in the extra three.
=> Adding the three extra card icon file names to description

content/dev/languages/what_to_translate.md
`includes/` missing in file path description in encapsulated plugin's new language file creation for plugin name and description.
=> Typo: 'includes/' missing in file path

assets/scss/_styles_project.scss
The default behaviour of the foldable menu icons (triangles) has, on hover/click, three states: 30, 60 & 90 deg. I think this is overkill (and a little weird). This PR proposes a simpler behaviour in that there is no change on hover and just a 90 deg change on click.
=> Change hover state of foldable menu icons

content/user/languages/updated_language_packs.md
Adding French Language to the list of supported language for ZC 1.58+ in updated_language_packs.md.
=> Adding French Language to the list of supported language for ZC 1.58+
