- Overview/main/introduction.md
broken link, character after colon.
> Fixes to main page

- Developer_Documentation/1.6/toc.md
- LEAD should be all upper case.
- Provide backlink to Introduction in toc.
> Small issues with TOC for 1.6

- Developer_Documentation/1.5.5/introduction.md
- Developer_Documentation/1.5.5/toc.md
- Developer_Documentation/1.6/introduction.md
- Developer_Documentation/intro/introduction.md
Make all pages navigable fromo TOC
Clearly indicate what page you are on in intro
> Build off Chris' re-org of Dev Doc pages

- Tutorials/main/introduction.md
- Tutorials/main/toc.md
- remove comment
- add introduction link to TOC
> Misc tutorial fixes

- Developer_Documentation/1.6/code_docs/admin_lead_pages/introduction.md
- Developer_Documentation/1.6/code_docs/dashboard_widgets/dashboard_widgets.md
This will allow the documentation to be relevant for longer.
> Changing "current" to "pre-1.6.0" to be more precise

- Developer_Documentation/v2/code_docs/admin_lead_pages/introduction.md
- Developer_Documentation/v2/code_docs/pagination/pagination.md
- Habitat/main/code_dev.md
- Habitat/main/customising.md
- Habitat/main/dev_tools.md
- Habitat/main/introduction.md
Some old references still existed.
> Updating docs to remove 160

- content/user/Email/logo.md
> with mis-spelled

- content/_index.html
Add links to legacy docs for easy reference until they are no longer needed.
Add link to main doc repo to help people get started contributing.
> Update main page

- content/user/All_Time_Favorites/_index.md
- content/user/First_Steps/basic_checklist.md
- content/user/First_Steps/how_do_i_install.md
- content/user/First_Steps/useful_tools.md
- content/user/Running/diagnosing_obscure_issues.md
- content/user/Security/SSL_cert.md
- content/user/Security/block_probes.md
- content/user/Security/hacked.md
- content/user/Security/pci_compliance.md
- content/user/Security/relocate_download_folder.md
- content/user/Security/securing_download_folder.md
- content/user/Security/security_recommendations.md
- content/user/Troubleshooting/blank_page.md
- content/user/Upgrading/convert_to_utf8.md
- content/user/Upgrading/detailed_upgrading.md
A couple of these articles need to have Wiki content remove - will do later.
> Security articles and articles they link to

- content/dev/Code/Modules/order_total_modules.md
- content/dev/Code/Modules/shipping_modules.md
I didn't want to modify Docsy so I just stuck the css in these files for now.  
There are also these annoying cases where you you have to escape the underscores to get defined constants to come out right.
> Fix formatting issues

- content/dev/Contributing/github_workflow.md
Update SourceTree instructions for Making a Working-Branch - to reflect latest version of Sourcetree
> Amend Github Workflow + Pull Requests

- content/user/All_Time_Favorites/_index.md
- content/user/Installing/enable_ssl.md
- content/user/Modules/authorizenet_aim.md
- content/user/Modules/authorizenet_sim.md
- content/user/Troubleshooting/error_71_maintenance_required.md
I have the corresponding Zen Cart code changes ready to go as soon as this is merged and I can double check the new URLs.
> Docs referenced in Zen Cart code

- assets/scss/_styles_project.scss
- assets/scss/_variables_project.scss
- content/_index.html
Beef up home page, get it to show all content without scrolling.
> Add links to various things

- content/user/customizing/add_pages.md
Forgot to mention the three define pages.
> Add more details to add pages section

- content/user/first_steps/database.md
- content/user/first_steps/hosting.md
- content/user/first_steps/where_is_backend.md
- content/user/first_steps/yes_you_need_ssl.md
- content/user/images/adding_multiple_images_to_a_product.md
- content/user/installing/enable_ssl.md
- content/user/installing/move_cart.md
- content/user/installing/permissions.md
- content/user/miscellaneous/configure.md
- content/user/miscellaneous/force_www.md
- content/user/orders/sales_analytics_affiliate_tools.md
- content/user/payment/payment_misc.md
- content/user/payment/paypal_misc.md
- content/user/products/attributes.md
- content/user/products/downloadable.md
- content/user/products/product_notification.md
- content/user/template/left_right_columns.md
- content/user/troubleshooting/blank_page.md
- content/user/troubleshooting/security_error.md
- content/user/troubleshooting/shipping_problems.md
- content/user/troubleshooting/warning_headers_already_sent.md
Or before block intended to start on a new line.
> Formatting - blank line before block to start on new line

- content/user/first_steps/hosting.md
Noticed CPanel should be cPanel
Wanted to clarify the SSL a little bit more with info I felt should be discussed in hosting now rather than after the certificate is purchased.
> CPanel to cPanel and more SSL info

- content/dev/code/Modules/order_total_modules.md
- content/dev/code/Modules/shipping_modules.md
- content/dev/code/creating_menu.md
- content/dev/code/init_system.md
- content/dev/code/notifiers.md
also some fixes for some formatting issues in dev.
> Change -> to > for greater readability  - dev side

- content/user/upgrading/detailed_upgrading.md
> fix formatting

- content/user/template/font_awesome.md
Cleaned up format and changed wording to remove old way of version 4
> Changed wording

- content/dev/contributing/introduction.md
I am making up some text for 0 level githubbers....
> remove bad Link to my first pull request

- content/user/first_steps/how_do_i_install.md
I think I managed to get the format correct.
Still not thrilled with having the individual create the configure files versus having zc_install do the work.
> Added cPanel Installation Instructions

- content/user/images/images_other_products.md
Putting items in order that they are addressed when creating a site.
> Changing Sort Order for Images Main Page

- content/user/products/downloadable.md
> Add AWS details

- assets/scss/_sidebar-tree.scss
- layouts/partials/sidebar-tree.html
> Docs site sidebar layout - patch for nested ul-li

- content/user/about_us/features.md
With the changes in contrast and the addition of noopener and noreferrer in offsite links, the responsive_classic template meets accessibility standards out of the box.
> Add Accessibility Compliance

- content/dev/contributing/coding_standards.md
- content/dev/plugins/encapsulated_plugins/sql_installation.md
- content/dev/schema/_index.md
- content/user/admin/master_password.md
- content/user/admin_pages/localization/languages.md
- content/user/admin_pages/reports/graphical_sales_report.md
- content/user/customizing/add_pages.md
- content/user/email/email_misc.md
- content/user/ezpages/ezpages_misc.md
- content/user/first_steps/how_do_i_install.md
- content/user/miscellaneous/can_zen_cart.md
- content/user/new_user_topics/no_such_file.md
- content/user/orders/orders_misc.md
- content/user/orders/sales_analytics_affiliate_tools.md
- content/user/performance/speed_up_site.md
- content/user/plugins/how_to_install_a_plugin.md
- content/user/plugins/why_plugins.md
- content/user/running/fixing_addresses.md
- content/user/running/login_as_customer.md
- content/user/template/template_misc.md
- content/user/troubleshooting/blank_page.md
- content/user/troubleshooting/diagnosing_obscure_issues.md
- content/user/troubleshooting/new_php_debug_logs.md
> Replace mod with plugin

- content/dev/plugins/encapsulated_plugins/converting.md
To indicate that you leave the new files in a folder admin . Added note and not sure if necessary but included zc_plugins to make the ./ be equivalent on both before and after (i.e. YOURSITE) hierarchy
not sure if it should be [YOURADMIN] is there a standard?
> Modify admin to YOURADMIN

- content/dev/languages/creating_a_language_pack.md
- content/dev/languages/updating_older_translation.md
I have moved update an older translation to a separate file. I left a link in the original page.
> Moved Update a translation to a seperate document

- content/dev/code/inclusion.md
- content/dev/code/notifiers.md
I ran out of gas writing the auto inclusion doc but I have meant to do this for a while.  Please throw out suggestions. 
At a minimum this is a start which can be built out over time.
> Update notifiers doc, add auto inclusion doc

- content/user/about_us/fake_solicitations.md
Warning people about bad guy phishing attempts.
> Fake warning page

- layouts/partials/footer-edit.html
- layouts/user/content.html
Chris, will this meet your needs for easy access to page editing?
> Prompt bug reporting and fixing in footer of content page

- content/user/payment/square.md
@drbyte please check and merge when approved.
> Square documentation

- content/user/first_steps/database.md
> database typo

- content/user/first_steps/overrides.md
> overrides type correction

- content/user/first_steps/glossary.md
I made two changes to text that I  think will help the explanations in two places.
> glossary text changes

- content/dev/code/updating_orders_status_history.md
> #514: Article on `zen_update_orders_history`.

- content/user/all_time_favorites/_index.md
I deliberately put the link at the top and not alphabetically. One needs this first.
> added documentation link

- content/user/first_steps/basic_checklist.md
- content/user/locations/_index.md
- content/user/taxes/_index.md
- content/user/taxes/canada_taxes.md
- content/user/taxes/default_tax_class.md
- content/user/taxes/tax_calc_wrong.md
- content/user/taxes/taxes.md
- content/user/taxes/us_taxes.md
> Move tax material to its own category

- content/user/upgrading/release_specific_upgrade_considerations.md
and removal of starting a sentence with "Because".
> Info for zen_parse_search_string, zen_get_countries

- content/user/upgrading/date_standardization.md
> Date standardization, aligning with current zc_install usage.

- content/dev/code/Modules/order_total_modules.md
https://www.zen-cart.com/showthread.php?227704-Create-a-shipping-module-for-only-some-products&p=1378438#post1378438
> add array to this->output in process function

- content/dev/code/notifiers.md
@drbyte please review.  I think this is easier to read.
> Restructure Observer-related loading documentation

- content/user/images/adding_multiple_images_to_a_product.md
If the title of a segment is not interrogatory, it should be in the proper title case. https://capitalizemytitle.com/
> Title Case should be consistent

- content/user/payment/payment_whoops_timeouts.md
- content/user/payment/paypal_ipn.md
> Separating out Whoops explanation

- content/user/customizing/add_pages.md
@drbyte please review changes.  We have discussed this before but it became top of mind after this plugin was added: https://www.zen-cart.com/downloads.php?do=file&id=1642
> Serving files from your cart

- content/user/template/disclosure_widget.md
Adding a new article on the use of a disclosure widget in /user/template/disclosure_widget.md
Edit: Apologies, I failed to read the contributing.md before submitting this PR so I may have been less than successful on some points. Better next time.
Sigh: To that end here is a preview link: [https://deploy-preview-737--zencartdocs.netlify.app/user/template/disclosure_widget/](url)
> How to use a disclosure widget to show/hide text

- content/user/payment/why_not_manual.md
- content/user/search/search_configs.md
- content/user/template/private_testing.md
- content/user/template/template_monster.md
- reasons to not use manual credit card processing
- using alternate templates
- details on template monster issues
- search configuration reference to search_in_description
> Small updates:

- content/user/first_steps/glossary.md
- content/user/localization/languages.md
- explain sub-zone
- link to language file change detail
> Small changes

- content/dev/languages/158_language_files.md
- content/user/email/advanced_email_troubleshooting.md
- content/user/email/email_transport_methods.md
- content/user/first_steps/server_requirements.md
- add to list of issues with langauge converter
- discussion of GMail, Highlight SPF and DKIM
- clarification of 1.5.8/PHP 8 interoperability
> Small improvements

- content/user/first_steps/server_requirements.md
- content/user/upgrading/date_standardization.md
- Fix broken link
- Example of bad date error log from customers table.
> Small tweaks

- content/dev/languages/158_language_files.md
- content/user/localization/158_language_files.md
- content/user/running/login_as_customer.md
- More details on 158 language files (plus better naming)
- Change "Login as Customer" to "Place Order" for better match to button text.
> Small fixes

- content/user/email/newsletters.md
Remove SendGrid, which is more of an ESP
> Newsletter providers list tweak

- content/dev/developer_environment.md
and flesh out/condense other information.
> Add developer email overrides

- content/user/payment/authorizenet_aim.md
> Updating link for Authorize account create

- content/release/changed_files-v1-5-5.html
- content/release/important_site_security_recommendations.html
Fixed in Zen Cart in this PR: 
https://github.com/zencart/zencart/pull/4790
> Fix typos in release docs

- assets/scss/_styles_project.scss
Fixes #779
Added missing search box to small screens, including minor homepage layout changes.
Files changed: /assets/scss/_styles_project.css
Edit: just noticed there should be a newline at the end of this file, should I resubmit?
> Search box on small screens

- content/user/new_user_topics/welcome.md
If the store owner deletes the Welcome message, the result is an Accessibility structure error of h1 to h3 with no h2, the Welcome message.
> Warning of Possible Accessibility Violation

- content/user/new_user_topics/congratulations.md
I thought I did this with the other "Welcome..." fix the other day.
It just warns them that they will get a structure error if the remove or comment out the h1 tag.
> Accessibility Warning

- layouts/partials/footer-edit.html
Fixes issue first reported in #905
> Fix error message

- assets/scss/_styles_project.scss
Fixes problem mentioned in #917
> White area at the bottom of Full Screen Main Page

- content/dev/code/php_updates.md
- content/dev/plugins/php_updating.md
- content/dev/plugins/upgrading_to_158.md
> Updates for PHP 8.2

- content/dev/release_process/version_stamping.md
- content/user/products/downloads_not_products.md
- .htaccess might need updating depending on the files you are serving
- remember to update the version.php in zc_install during a build.
> Small updates

- content/dev/plugins/upgrading_to_158.md
Suggested update re zcDate as i had to work this out.
> Update to zcDate Wording Include Global.

- content/user/email/customizing_email.md
Correct line numbers and code for plain text email zc 1.5.8 Add text to strengthen, do not change core file message.
Update customizing_email.md
> Correct line References for 1.5.8,

- content/dev/code/notifiers.md
The load point change to 200 prior to 1.5.7 so have updated to 200.
> Change load point to 200

- content/user/email/advanced_email_troubleshooting.md
A more thorough listing of required, best-to-have, and optional email accounts.  Also, recommended do's and don't's for Forwards and Autoresponders.
> Include Role Emails, Redirects/Forwards and AUtoresponders under Email

- content/user/troubleshooting/blocking_attacks.md
Let me know if we need to explain WHM here or somewhere else.
> CSF/cPHulk Definitions and Instructions

- content/dev/code/init_system.md
Fixes #1025
Correcting code used to load an `init_script` in Developer Docs
> Correcting control array code

- content/user/payment/square.md
- content/user/payment/square_payments_form.md
Partially fixes https://github.com/zencart/documentation/issues/1016
Small edits and addition of pertinent information on Refunds/Captures/Voids from 'Recommended Services' forum page (https://www.zen-cart.com/content.php?349-Square-Payments-for-Zen-Cart)
> Square payment webpay edits

- content/dev/release_process/dependency_checks.md
Also add remarks from Chris (not required to be on latest version, just be sure we have security patches).
> Add links for dependency checking

- assets/scss/_variables_project.scss
> Ensure breadcrumbs visible on desktop

- content/user/accessibility/accessibility.md
- content/user/accessibility/concerns/aria_labels.md
- content/user/accessibility/concerns/color_contrast.md
This finishes the Concerns items and, when adding the links to the Accessibility page, I also added the links for text I'll be adding later.
> Finish Concerns and Prepare Accessibility Page

- content/user/admin_pages/configuration/configuration_productinfo.md
- content/user/products/product_edit.md
I would also put this info in the edit page as it seems completely unintuitive.
> Update qty_box info

- assets/scss/_styles_project.scss
- layouts/partials/hooks/body-end.html
- layouts/partials/hooks/head-end.html
- layouts/partials/search-input.html
Fixes #1119
Upgrading Algolia DocSearch v2 to v3
> Algolia Search Upgrade

- content/user/admin_pages/configuration/configuration_ezpagessettings.md
- content/user/admin_pages/configuration/configuration_logging.md
- content/user/admin_pages/configuration/configuration_maximumvalues.md
- content/user/admin_pages/configuration/configuration_minimumvalues.md
- content/user/admin_pages/configuration/configuration_mystore.md
Ref: #1124 
Exploring to see what Algolia actually indexes and how they render it.
> Testing search fix for htmlentities

- content/user/admin_pages/configuration/configuration_creditcards.md
- content/user/admin_pages/configuration/configuration_customerdetails.md
- content/user/admin_pages/configuration/configuration_definepagestatus.md
- content/user/admin_pages/configuration/configuration_email.md
> Search test2

- content/user/admin_pages/configuration/configuration_alllisting.md
- content/user/admin_pages/configuration/configuration_attributesettings.md
- content/user/admin_pages/configuration/configuration_creditcards.md
- content/user/admin_pages/configuration/configuration_definepagestatus.md
- content/user/admin_pages/configuration/configuration_email.md
- content/user/admin_pages/configuration/configuration_ezpagessettings.md
- content/user/admin_pages/configuration/configuration_featuredlisting.md
- content/user/admin_pages/configuration/configuration_gvcoupons.md
- content/user/admin_pages/configuration/configuration_gzipcompression.md
- content/user/admin_pages/configuration/configuration_images.md
- content/user/admin_pages/configuration/configuration_indexlisting.md
- content/user/admin_pages/configuration/configuration_layoutsettings.md
- content/user/admin_pages/configuration/configuration_logging.md
- content/user/admin_pages/configuration/configuration_maximumvalues.md
- content/user/admin_pages/configuration/configuration_minimumvalues.md
- content/user/admin_pages/configuration/configuration_mystore.md
- content/user/admin_pages/configuration/configuration_newlisting.md
- content/user/admin_pages/configuration/configuration_productinfo.md
- content/user/admin_pages/configuration/configuration_productlisting.md
- content/user/admin_pages/configuration/configuration_regulations.md
- content/user/admin_pages/configuration/configuration_sessions.md
- content/user/admin_pages/configuration/configuration_shippingpackaging.md
- content/user/admin_pages/configuration/configuration_stock.md
- content/user/admin_pages/configuration/configuration_websitemaintenance.md
> Refresh config help pages with new separator

- content/user/admin_pages/configuration/all.md
> change separator

- content/user/order_total/coupons.md
As requested on PR #6178 for Discussion #5856, docs for the 2 new auto-apply coupon features.
> Automatic coupon application.

- config.toml
> Add footer link to support site forum

- content/user/seo/deleted_product_redirects.md
Despite there being a world of info out there on .htaccess, getting redirects to work as expected proved incredibly frustrating and time-consuming, due to lack of experience/not seeing anything about rewrites being processed first until late in the day, and urls being separate to the query parameters. So this is an attempt to document that and hopefully prevent others' frustration.
No doubt more experienced users can add more.
> example htaccess redirects

- content/user/locations/zone_definitions.md
> Update zone_definitions.md typo

- content/user/sideboxes/add_link_information_sidebox.md
- content/user/sideboxes/ezpages_sidebox.md
- content/user/sideboxes/more_information_sidebox.md
See these Zen Cart PRs for additional information
1. https://github.com/zencart/zencart/pull/6443
2. https://github.com/zencart/zencart/pull/6451
> Document how to use sidebox notifications

- content/release/_index.md
- content/release/archive_changed/_index.md
- content/release/archive_whatsnew/_index.md
- static/_redirects
> Trying to improve the names of archives

- assets/scss/_styles_project.scss
- assets/scss/_variables_project.scss
- content/user/about_us/whats_new.md
Reducing number of colors used; using complementary (or otherwise related) colors.
> Trying a single palette

- content/release/whatsnext.md
- content/user/_index.md
- content/user/customizing/site_specific_overrides.md
- content/user/images/additional_images.md
- content/user/images/image_filename_conventions.md
- content/user/upgrading/release_specific_upgrade_considerations.md
Updates related to next release.
> v 2.1.0 changes

- content/release/whatsnext.md
- content/user/about_us/security_releases.md
- content/user/about_us/whats_new.md
- content/user/miscellaneous/can_zen_cart.md
- content/user/payment/payment.md
- content/user/running/posm.md
- content/user/running/stock.md
- content/user/security/plugin_patches.md
- content/user/security/security_patches.md
- content/user/shipping/shipping.md
- layouts/shortcodes/security_updates.md
> CKEditor updates

- content/user/about_us/whats_new.md
- content/user/miscellaneous/can_zen_cart.md
- content/user/upgrading/multiple_php_versions.md
Additions to multiple PHP versions about htaccess
> Small fixes to what's new and can zen cart

- content/user/payment/paypal_express_checkout.md
Thanks to @drbyte for these corrections.
> Fix old PayPal instructions

- content/dev/languages/what_to_translate.md
Detailed information on how to find and convert English languages strings in database to make translation of admin menus easier.
> Tools for translation of English strings in database

- content/dev/languages/what_to_translate.md
> 2 typos and 1 rephrasing in 'What to Translate'

- content/dev/languages/what_to_translate.md
Added some missing information and corrected two regular expressions.
> Optimized and corrected some regular expressions

- content/user/localization/changing_weight_to_kg.md
- content/user/localization/uk_language_overide_files.md
- content/user/template/basic_customizations.md
Add lbs to kg and uk customisation files
Scott I think you asked for these some time ago. I have just got around to doing them.
Please check I have the formatting and linking correct.
> Add uk customisation document and lbs to kg

- content/user/shipping/usps.md
Expanded the steps on how to use and install the USPS Restful module.
> Adding details to the USPS Restful version

- content/user/accessibility/concerns/aria_labels.md
- content/user/accessibility/tools/andi.md
- content/user/accessibility/tools/devtools.md
- content/user/accessibility/tools/siteimprove.md
- content/user/accessibility/tools/wave.md
The number of available browser extensions for the some of the [Accessibility Tools](https://docs.zen-cart.com/user/accessibility/tools/) have changed. Rather than specifically mention a browser's name, a link is provided to the provider's website (where possible) wherein an up-to-date listing of extensions can be found.
> Accessibility Tools, updating browser extensions

- content/dev/plugins/encapsulated_plugins/converting.md
See https://github.com/zencart/zencart/issues/7062.
> Note that encapsulated plugins require array lang-files (zc210+)
